### PR TITLE
Typo in WordPress name/brand

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by timwhitlock** [comment]
This typo will have to be amended in all the translation files, or this commit will be broken. I'll do this myself on the next update.

**Comment by pedro-mendonca** [comment]
Ok.
Another question, do you build loco-translate-xx:XX.js files in /pub/js/lang automatically? It's redundant and a lot of work there without poedit.

**Comment by timwhitlock** [comment]
Yes, I have a script to build the JS files. The build script is not in the repo because it also includes code extraction from the Loco core codebase which is not public. 

I suppose I should split the language builders out at some point and add them in here.

**Comment by pedro-mendonca** [comment]
Ok, than I'll just pull my new language files.

**Pull request closed without merging**
